// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYr8_3wtuyf5HBUeegmth6AQX-yBxatTg',
    appId: '1:795806628804:web:2f7b3e7e924862f0244291',
    messagingSenderId: '795806628804',
    projectId: 'movie-301cf',
    authDomain: 'movie-301cf.firebaseapp.com',
    storageBucket: 'movie-301cf.appspot.com',
    measurementId: 'G-9GP9W1Q5GS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8TSWFZmxJDKl0pByuGvUIbYkM8ZDdoRA',
    appId: '1:795806628804:android:699430becafebc44244291',
    messagingSenderId: '795806628804',
    projectId: 'movie-301cf',
    storageBucket: 'movie-301cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4K3eIxQUGhgVdXeZ4a3SJiSGsdmhcAL0',
    appId: '1:795806628804:ios:e201db1a9b1547cd244291',
    messagingSenderId: '795806628804',
    projectId: 'movie-301cf',
    storageBucket: 'movie-301cf.appspot.com',
    iosClientId: '795806628804-neaqesrjbpcncr0u63l98ruscdqsii6a.apps.googleusercontent.com',
    iosBundleId: 'com.example.myfirstapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4K3eIxQUGhgVdXeZ4a3SJiSGsdmhcAL0',
    appId: '1:795806628804:ios:e201db1a9b1547cd244291',
    messagingSenderId: '795806628804',
    projectId: 'movie-301cf',
    storageBucket: 'movie-301cf.appspot.com',
    iosClientId: '795806628804-neaqesrjbpcncr0u63l98ruscdqsii6a.apps.googleusercontent.com',
    iosBundleId: 'com.example.myfirstapp',
  );
}
